/**
 * @author Rhonda Marshall
 * Nov 1, 2015
 * 
 * The Loaded class implements the Die interface
 * therefore this class must provide all the methods that are
 * specified by the Die interface with the exact signatures
 * specified and with the same return type.
 * 
 * Those methods are
 *      void roll();
 *      int getValue();
 * 
 */
package dnddiceroller;

import java.util.Random;

/**
 *
 * @author Rhonda Marshall
 * Nov 1, 2015
 */

public class Loaded implements Die {
    private int numberOfSides;             // number of sides on the dice
    private int value;                     // value generated by a random number 
    private int loadedSide;                // the loaded side of the dice
    
    /**
     * Constructor
     * @param numberOfSides     The numberOfSides on the dice
     * @param loadedSide        The side of the dice that is loaded
     */
    public Loaded(int numberOfSides, int loadedSide) {
        this.numberOfSides = numberOfSides;
        this.value = 0;
        this.loadedSide = loadedSide;
    } // Loaded constructor
    
    /**
     * The roll method (Required by Die interface)
     * The random number number will determine the face of the dice that
     * lands down
     * 
     * The random number will be a value between 1 and 10
     * If the random number is 6 to 10, the face will be the loadedSide variable
     * otherwise the face will be the random number
     * This is a 50% probability the dice will land on the loaded side
     * 
     * Sets the Loaded objects value field to be the value of the face of 
     * the die that is up
     
     * I am assuming a loaded dice is a 6 sided numbered dice
     */
    @Override
    public void roll() {
        Random randomNumber = new Random();
        this.value = randomNumber.nextInt(10) + 1;
        
        if (this.value >= 6 && this.value <= 10)
            this.value = this.getLoadedSide();
        
        // System.out.printf("loaded side %d, down side is %d\n", this.getLoadedSide(), this.value);
        
        this.value = this.numberOfSides - this.value + 1;
        
        // System.out.printf("up side is %d\n", this.value);
        
    } // roll method
    
    
    /**
     * getValue accessor method (Required by Die interface)
     * @return  The Loaded objects value
     */
    @Override
    public int getValue(){
        return this.value;
    } // getValue method
    
    /**
     * getLoadedSide accessor method
     * @return Loaded objects loadedSide
     */
    private int getLoadedSide() {
        return this.loadedSide;
    } // getLoadedSide method
    
} // LoadedDie class

  
       
