package dnddiceroller;

import java.util.Random;

/**
 * @author Rhonda Marshall
 * Nov 1, 2015
 * 
 * The NumberedDie class implements the Die interface
 * therefore this class must provide all the methods that are
 * specified by the Die interface with the exact signatures
 * specified and with the same return type.
 * 
 * Those methods are
 *      void roll();
 *      int getValue();
 * 
 */
public class NumberedDie implements Die {
    private int numberOfSides;             // number of sides on the dice
    private int value;                     // value generated by a random number 
    
    /**
     * Constructor
     * @param numberOfSides     The numberOfSides on the dice
     */
    public NumberedDie(int numberOfSides) {
        this.numberOfSides = numberOfSides;
        this.value = 0;
    } // NumberedDie constructor
    
    /**
     * The roll method (Required by Die interface)
     * Calculates a random number between the value
     * of one and the NumberedDie objects numberOfSides field.
     * Sets the NumberedDie objects value field to equal the random number
     */
    @Override
    public void roll() {
        Random randomNumber = new Random();
        this.value = randomNumber.nextInt(this.numberOfSides) + 1;   
    } // roll method
    
    
    /**
     * getValue accessors method (Required by Die interface)
     * @return  The NumberedDie objects value
     */
    @Override
    public int getValue(){
        return this.value;
    } // getValue method
       
} // NumberedDie class

